
name: jlp
version: '19.1'
summary: Jenkins Launchpad Plugin
description: |
  Launchpad plugin for Jenkins
base: core18
grade: stable
confinement: strict

apps:
  launchpadTrigger:
    command: bin/launchpadTrigger
    plugs: [home, network, network-bind]

parts:
  tarmac:
    plugin: dump
    source:  https://git.launchpad.net/tarmac
    source-type: git
    source-branch: 'master'
    override-prime: |
      :
  patch:
    plugin: dump
    source: patches
    override-prime: |
      :
  jlp:
    after: [tarmac, patch]
    plugin: python
    python-version: python3
    source: https://git.launchpad.net/jenkins-launchpad-plugin
    source-type: git
    source-branch: 'master'
    stage-packages:
      - python3-configobj
      - python3-six
      - python3-pip
    build-packages:
      - build-essential
      - python3
      - python3-all
      - python3-dev
      - python3-pip
      - zlib1g
    python-packages:
      - breezy
      - python-jenkins
      - Jinja2
      - launchpadlib
      - lockfile
      - requests
      - setuptools
      - python-git
      - PyYAML
    override-build: |
      mv ${SNAPCRAFT_STAGE}/tarmac \
        ${SNAPCRAFT_PART_INSTALL}/lib/python3.6/site-packages/
      patch -u ${SNAPCRAFT_PART_BUILD}/jlp/commands/launchpadTrigger.py \
        -i ${SNAPCRAFT_PART_BUILD}/../../patch/src/0001-jlp-commands-launchpadTrigger.patch
      patch -u ${SNAPCRAFT_PART_BUILD}/jlp/jsonjenkins.py \
        -i ${SNAPCRAFT_PART_BUILD}/../../patch/src/002-jlp-jsonjenkins.patch
      rm -rf ${SNAPCRAFT_STAGE}/*
      snapcraftctl build
    override-prime: |
      snapcraftctl prime
      echo "Compiling pyc files..."
      ${SNAPCRAFT_PRIME}/usr/bin/python3 -m compileall \
       -q ${SNAPCRAFT_PRIME}
